version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: attendance440-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: attendance_db
    ports:
      - "5603:5432"
    volumes:
      - pgdata_att40:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - attendance-net

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: attendance40-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: attendance_db
      DB_USER: postgres
      DB_PASSWORD: admin123
      PORT: 3603
    ports:
      - "3603:3603"
    networks:
      - attendance-net

  employee-attendance:
    build:
      context: ./Employee-Attendance
      dockerfile: Dockerfile
    container_name: attendance40-ui-employee
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8606:80"
    networks:
      - attendance-net

  hr-attendance:
    build:
      context: ./HR-Attendance
      dockerfile: Dockerfile
    container_name: attendance40-ui-hr
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8607:80"
    networks:
      - attendance-net

networks:
  attendance-net:

volumes:
  pgdata_att40:

